### ISSUE TITLE
Incorrect command building causes failure to launch on Windows

### ISSUE THREAD

**Issue by LooFifteen** [mworzala/mc-cli#10]
Does not launch at all due to how the command is built. As Windows' paths contain `:` to specify the drive, using `:` to separate classpath jars will not work on Windows builds of Java. Instead, `;` should be used. Semicolons should also work on Linux and Mac.

`internal/pkg/game/launch/launch.go:62`
```diff
-classpath.WriteString(":")
+classpath.WriteString(";")
```

On top of this, Windows Java builds do not know about the `-XstartOnFirstThread` flag. Because of this, Java will exit immediately when provided. To work on Windows it must be removed when launching on Windows:

`internal/pkg/game/launch/launch.go:105`
```diff
-args = append(args, "-XstartOnFirstThread")
```

Platform: Windows
Version: From source

Relevantish stacktrace:
```
Unrecognized option: -XstartOnFirstThread
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by mworzala** [comment]
I do not like windows (re the first one), the second one is just a bit of an oops. The launch logic is pretty yikes at the moment, I need to clean it up a lot. But I can fix these in the mean time.

**Comment by LooFifteen** [comment]
Neither do I. These changes get it to launch properly on my Windows machine.

**Comment by mworzala** [comment]
I didn't make exactly the suggested changes because they would break it on macOS :) but it should work now

**Comment by LooFifteen** [comment]
This fix has induced another bug. `internal/pkg/game/launch/launch.go:58` should not have been changed with the patch.
